### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by Link2Twenty** [Link2Twenty/l2t-paper-color#1]
Perhaps have it come out of a paper-input or a FAB?
Perhaps it can come from either

**Stage 1:**
http://www.materialdoc.com/color-picker/
https://material.uplabs.com/posts/material-color-picker-library-for-android

**Advanced:**
https://material.uplabs.com/posts/android-material-color-picker-dialog

**Comment by Link2Twenty** [comment]
**Elements:**
https://www.webcomponents.org/element/PolymerElements/paper-dialog-behavior
https://www.webcomponents.org/element/PolymerElements/paper-fab
https://www.webcomponents.org/element/PolymerElements/paper-input
https://www.webcomponents.org/element/PolymerElements/iron-icons
https://www.webcomponents.org/element/PolymerElements/paper-slider
https://www.webcomponents.org/element/PolymerElements/paper-button
https://www.webcomponents.org/element/PolymerElements/paper-styles

**Comment by Link2Twenty** [comment]
This element should be made up of several elements, I propose the following.

- [x] **Color blobs**: [l2t-paper-color-radio](https://github.com/Link2Twenty/l2t-paper-color/issues/2)
_Each color circle should be a radio button in a radio group, may as well make this an element as we'll have to use it a lot._



 - [x] **Default picker**: [l2t-paper-color-picker](https://github.com/Link2Twenty/l2t-paper-color/issues/3)
_This will be the box containing all the preselected colors, it will also include an option to move to advanced._

- [x] **Advanced picker**: [l2t-paper-color-advanced](https://github.com/Link2Twenty/l2t-paper-color/issues/4)
_This will be the advanced screen, with a slider for each color RGB with a live preview window._

- [x] **Color dialog**: [l2t-paper-color-dialog](https://github.com/Link2Twenty/l2t-paper-color/issues/5)
_A dialog box to bring picker and advanced together._

**Comment by Link2Twenty** [comment]
The dialog fires an event when closed something like this could catch it

```JS
document.addEventListener('paper-color-dialog-closed', function(e) { 
  if(e.detail){
    console.log(e.target.color)
  }else{
    return
  } 
}, false);
```
